### ISSUE TITLE
Table names forced to lowercase in Discovery; Names with caps then skipped in compare

### ISSUE THREAD

**Issue by c-simpson** [CrunchyData/pgCompare#22]
**Describe the issue:**

PG Tables with names that include capital letters are forced to lower case and stored that way in dc_table.    
When Compare operation is run, those tables are reported as `Status = skipped`

**Describe the expected behavior:**

Table names should be stored and compared regardless of naming convention. 

Tested by re-naming sample `emp` table in sample database to `Emp` . `Emp` skipped, `location` compared

**Tell us about your environment:**

Source Database:
- RDBMS Type: Postgres
- Version: 15

Target Database:
- RDBMS Type: Postgres
- Version: 15

Source Table DDL:
```
CREATE TABLE pgctest."Emp" (
	eid int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	first_name varchar(40) NULL,
	last_name varchar(40) NULL,
	email varchar(100) NULL,
	hire_dt date NULL,
	age int4 NULL,
	zip int4 NULL,
	status bpchar(3) NULL,
	salary numeric(12, 2) NULL,
	last_login timestamp NULL,
	bio text NULL,
	CONSTRAINT "Emp_pkey" PRIMARY KEY (eid)
);
```

Target Table DDL:
```
CREATE TABLE pgctest2."Emp" (
	eid int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	first_name varchar(40) NULL,
	last_name varchar(40) NULL,
	email varchar(100) NULL,
	hire_dt date NULL,
	age int4 NULL,
	zip int4 NULL,
	status bpchar(3) NULL,
	salary numeric(12, 2) NULL,
	last_login timestamp NULL,
	bio text NULL,
	CONSTRAINT "Emp_pkey" PRIMARY KEY (eid)
);
```

**Comment by cbrianpace** [comment]
Thanks for the detailed information.  I will take a look at this and hope to have a fix ready by the end of the week.

**Comment by cbrianpace** [comment]
@c-simpson I just pushed a change to temporarily address the issue with the table name.  After doing the table discovery, you will need to adjust the table name in the dc_table.source_table and dc_table.target_table columns (modify the value from emp to Emp).  Also added a note to the README to reflect the same.

As it turns out, digging into this there are greater challenges.  For now, just solving for mixed case.  Will start work on the greater opportunities to compliment this one (i.e. columns with reserved words and mixed case, Oracle tables in lower case, postgres tables in upper case, etc).

Let me know if the fix works for you.  Thanks again for raising the issue.

**Comment by c-simpson** [comment]
Thanks Brian, I'll check it out.

**Comment by cbrianpace** [comment]
@c-simpson were you able to see if this last PR fixed your case issue?
